services:
  - type: web
    runtime: node
    name: portfolio-new
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
